#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'


require 'strscan'
require 'pp'

class NStackRadiusParser < Racc::Parser

module_eval(<<'...end n_stack_radius_parser.ry/module_eval...', 'n_stack_radius_parser.ry', 63)

def parse(str)
    scanner = StringScanner.new(str)
    @q = []
    while !scanner.eos?
        scanner.scan(/[\s\n]+/)
        scanner.scan(/phase/) ?                     @q << [:PHASE, :PHASE] :
        scanner.scan(/true/) ?                      @q << [:BOOLEAN, true] :
        scanner.scan(/false/) ?                     @q << [:BOOLEAN, false] :
        scanner.scan(/do/) ?                        @q << [:DO, :do] :
        scanner.scan(/goto/) ?                      @q << [:GOTO, :goto] :

        scanner.scan(/\".*?\"/) ?                   @q << [:STRING, scanner.matched[1..-2]] :
        scanner.scan(/\'.*?\'/) ?                   @q << [:STRING, scanner.matched[1..-2]] :
        scanner.scan(/[a-zA-Z_][a-zA-Z0-9_]*/) ?    @q << [:IDENTIFIER, scanner.matched.to_s] :
        scanner.scan(/([0-9]*\.[0-9]+)/) ?          @q << [:NUMBER, scanner.matched.to_f] :
        scanner.scan(/(0|[1-9][0-9]*)/) ?           @q << [:NUMBER, scanner.matched.to_i] :
        scanner.scan(/./) ?                         @q << [scanner.matched, scanner.matched] :
        raise("parse error")
    end
    tree = do_parse
    pp tree
    convert(tree)
end

def next_token
    @q.shift
end

def convert(tree)
    stack = [tree]
    operations = []
    while !stack.empty?
        node = stack.pop()
        #puts "NODE:#{node[0]}"
        #puts "CHILDREN:#{node[2]}"
        case node[0]
            when :phase # フェイズは特別な処理を行う
                node[2].each do |child|
                    stack.push(child)
                end
                operations.push([:phase, convert(node[1]), node[2].length])

            when :do
                node[2].each do |child|
                    stack.push(child)
                end
                operations.push([:do, convert(node[1]), node[2].length])

            else        # それ以外は同じ
                if node[2]
                    node[2].each do |child|
                        stack.push(child)
                    end
                    operations.push([node[0], node[1], node[2].length])
                else
                    operations.push([node[0], node[1], 0])
                end
        end
    end
    operations
end

...end n_stack_radius_parser.ry/module_eval...
##### State transition tables begin ###

racc_action_table = [
    26,    27,    28,    24,    25,    11,    21,    29,     9,    17,
    30,    18,    19,    20,    22,    30,    49,    22,     8,    48,
    17,     3,    18,    19,    20,    18,    19,    20,     8,     8,
     6,    32,     8,    18,    19,    20,    18,    19,    20,    23,
     8,     8,     5,     8,    18,    19,    20,    18,    19,    20,
   nil,     8,   nil,   nil,     8,    18,    19,    20,    18,    19,
    20,   nil,     8,   nil,    46,     8,    18,    19,    20,    47,
    37,   nil,   nil,     8,    18,    19,    20,    26,    27,    28,
   nil,     8,    26,    27,    28,    24,    25,    26,    27,    28,
    24,    25,    26,    27,    28,    24,    25,    26,    27,    28,
    24,    25,    26,    27,    28 ]

racc_action_check = [
    44,    44,    44,    44,    44,    10,    12,    15,     7,    10,
    35,    10,    10,    10,    12,    15,    45,    36,    10,    44,
    45,     1,    45,    45,    45,    25,    25,    25,     5,    45,
     3,    21,    25,    27,    27,    27,    30,    30,    30,    13,
    27,    17,     2,    30,    46,    46,    46,    26,    26,    26,
   nil,    46,   nil,   nil,    26,    29,    29,    29,    28,    28,
    28,   nil,    29,   nil,    34,    28,    22,    22,    22,    34,
    22,   nil,   nil,    22,    24,    24,    24,    39,    39,    39,
   nil,    24,    50,    50,    50,    50,    50,    14,    14,    14,
    14,    14,    33,    33,    33,    33,    33,    43,    43,    43,
    43,    43,    38,    38,    38 ]

racc_action_pointer = [
   nil,    21,    35,    30,   nil,     6,   nil,     0,   nil,   nil,
    -4,   nil,    -4,    28,    85,    -5,   nil,    19,   nil,   nil,
   nil,    23,    51,   nil,    59,    10,    32,    18,    43,    40,
    21,   nil,   nil,    90,    50,   -10,    -1,   nil,   100,    75,
   nil,   nil,   nil,    95,    -2,     7,    29,   nil,   nil,   nil,
    80 ]

racc_action_default = [
    -2,   -29,    -1,   -29,    -3,   -29,    51,   -29,   -28,    -6,
   -29,    -4,   -26,    -7,    -9,   -23,   -11,   -29,   -20,   -21,
   -22,   -29,   -29,    -8,   -29,   -29,   -29,   -29,   -29,   -29,
   -29,   -12,    -6,   -13,   -29,   -23,   -26,   -24,   -15,   -16,
   -17,   -18,   -19,   -10,   -29,   -29,   -29,   -25,   -27,    -5,
   -14 ]

racc_goto_table = [
     7,    15,    10,    34,     2,    12,     4,     1,   nil,   nil,
   nil,    33,    31,    38,    39,    40,    41,    42,    43,    44,
   nil,   nil,   nil,   nil,   nil,    45,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    50,    15,   nil,   nil,   nil,
    12 ]

racc_goto_check = [
     4,     9,     5,    10,     2,     4,     3,     1,   nil,   nil,
   nil,     8,     4,     8,     8,     8,     8,     8,     8,     8,
   nil,   nil,   nil,   nil,   nil,     5,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,     8,     9,   nil,   nil,   nil,
     4 ]

racc_goto_pointer = [
   nil,     7,     4,     4,    -5,    -7,   nil,   nil,   -11,    -9,
   -19 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,    36,   nil,    16,    13,    14,    35,
   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 24, :_reduce_1,
  0, 25, :_reduce_2,
  2, 25, :_reduce_3,
  5, 26, :_reduce_4,
  5, 29, :_reduce_5,
  0, 28, :_reduce_6,
  2, 28, :_reduce_7,
  3, 28, :_reduce_8,
  1, 30, :_reduce_none,
  3, 30, :_reduce_10,
  1, 30, :_reduce_none,
  2, 30, :_reduce_12,
  1, 33, :_reduce_13,
  3, 33, :_reduce_14,
  3, 31, :_reduce_15,
  3, 31, :_reduce_16,
  3, 31, :_reduce_17,
  3, 31, :_reduce_18,
  3, 31, :_reduce_19,
  1, 31, :_reduce_20,
  1, 31, :_reduce_21,
  1, 31, :_reduce_22,
  1, 31, :_reduce_23,
  3, 31, :_reduce_24,
  4, 31, :_reduce_25,
  1, 32, :_reduce_26,
  4, 32, :_reduce_27,
  1, 27, :_reduce_28 ]

racc_reduce_n = 29

racc_shift_n = 51

racc_token_table = {
  false => 0,
  :error => 1,
  "*" => 2,
  "/" => 3,
  "%" => 4,
  "+" => 5,
  "-" => 6,
  :PHASE => 7,
  "{" => 8,
  "}" => 9,
  :DO => 10,
  ";" => 11,
  "=" => 12,
  :GOTO => 13,
  "," => 14,
  :NUMBER => 15,
  :STRING => 16,
  :BOOLEAN => 17,
  "(" => 18,
  ")" => 19,
  "[" => 20,
  "]" => 21,
  :IDENTIFIER => 22 }

racc_nt_base = 23

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "\"*\"",
  "\"/\"",
  "\"%\"",
  "\"+\"",
  "\"-\"",
  "PHASE",
  "\"{\"",
  "\"}\"",
  "DO",
  "\";\"",
  "\"=\"",
  "GOTO",
  "\",\"",
  "NUMBER",
  "STRING",
  "BOOLEAN",
  "\"(\"",
  "\")\"",
  "\"[\"",
  "\"]\"",
  "IDENTIFIER",
  "$start",
  "program",
  "phases",
  "phase",
  "identifier",
  "statements",
  "do",
  "statement",
  "expr",
  "variable_address",
  "arguments" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 8)
  def _reduce_1(val, _values, result)
    result = [:program, nil, [val[0]]]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 11)
  def _reduce_2(val, _values, result)
    result = [:phases, nil, []]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 12)
  def _reduce_3(val, _values, result)
    result[2] << val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 15)
  def _reduce_4(val, _values, result)
    result = [:phase, val[3], [val[1]]]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 18)
  def _reduce_5(val, _values, result)
    result = [:do, val[3], [val[0]]]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 21)
  def _reduce_6(val, _values, result)
    result = [:statements, nil, []]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 22)
  def _reduce_7(val, _values, result)
    result[2] << val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 23)
  def _reduce_8(val, _values, result)
    result[2] << val[1]
    result
  end
.,.,

# reduce 9 omitted

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 27)
  def _reduce_10(val, _values, result)
    result = [:assign_variable, nil, [val[0], val[2]]]
    result
  end
.,.,

# reduce 11 omitted

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 29)
  def _reduce_12(val, _values, result)
    result = [:goto, nil, [val[1]]]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 32)
  def _reduce_13(val, _values, result)
    result = [:arguments, nil, [val[0]]]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 33)
  def _reduce_14(val, _values, result)
    result[2] << val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 36)
  def _reduce_15(val, _values, result)
    result = [:add, nil, [val[0], val[2]]]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 37)
  def _reduce_16(val, _values, result)
    result = [:dif, nil, [val[0], val[2]]]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 38)
  def _reduce_17(val, _values, result)
    result = [:mul, nil, [val[0], val[2]]]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 39)
  def _reduce_18(val, _values, result)
    result = [:div, nil, [val[0], val[2]]]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 40)
  def _reduce_19(val, _values, result)
    result = [:mod, nil, [val[0], val[2]]]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 41)
  def _reduce_20(val, _values, result)
    result = [:number, val[0], nil]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 42)
  def _reduce_21(val, _values, result)
    result = [:string, val[0], nil]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 43)
  def _reduce_22(val, _values, result)
    result = [:boolean, val[0], nil]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 44)
  def _reduce_23(val, _values, result)
    result = [:reference_variable, nil, [val[0]]]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 45)
  def _reduce_24(val, _values, result)
    result = [:call_function, nil, [val[0]]]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 46)
  def _reduce_25(val, _values, result)
    result = [:call_function, nil, [val[0], val[2]]]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 49)
  def _reduce_26(val, _values, result)
    result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 50)
  def _reduce_27(val, _values, result)
    result = [:index, nil, [val[0], val[2]]]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 53)
  def _reduce_28(val, _values, result)
    result = [:identifier, val[0], nil]
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class NStackRadiusParser


if __FILE__ == $0
    parser = NStackRadiusParser.new
    prg = ""
    File.open("program.rlb", "r") do |f|
        prg = f.read.chomp
    end
    pp parser.parse(prg)

end
