#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'


require 'strscan'
require 'pp'

class NStackRadiusParser < Racc::Parser

module_eval(<<'...end n_stack_radius_parser.ry/module_eval...', 'n_stack_radius_parser.ry', 54)

def parse(str)
    scanner = StringScanner.new(str)
    @q = []
    while !scanner.eos?
        scanner.scan(/[\s\n]+/)
        scanner.scan(/phase/) ?                     @q << [:PHASE, :PHASE] :
        scanner.scan(/true/) ?                      @q << [:BOOLEAN, true] :
        scanner.scan(/false/) ?                     @q << [:BOOLEAN, false] :
        scanner.scan(/do/) ?                        @q << [:DO, :do] :
        scanner.scan(/goto/) ?                      @q << [:GOTO, :goto] :

        scanner.scan(/\".*?\"/) ?                   @q << [:STRING, scanner.matched[1..-2]] :
        scanner.scan(/\'.*?\'/) ?                   @q << [:STRING, scanner.matched[1..-2]] :
        scanner.scan(/[a-zA-Z_][a-zA-Z0-9_]*/) ?    @q << [:IDENTIFIER, scanner.matched.to_s] :
        scanner.scan(/([0-9]*\.[0-9]+)/) ?          @q << [:NUMBER, scanner.matched.to_f] :
        scanner.scan(/(0|[1-9][0-9]*)/) ?           @q << [:NUMBER, scanner.matched.to_i] :
        scanner.scan(/./) ?                         @q << [scanner.matched, scanner.matched] :
        raise("parse error")
    end
    tree = do_parse
    pp tree
    convert(tree)
end

def next_token
    @q.shift
end

def convert(tree)
    stack = [tree]
    operations = []
    while !stack.empty?
        node = stack.pop()
        #puts "NODE:#{node[0]}"
        #puts "CHILDREN:#{node[2]}"
        case node[0]
            when :phase # フェイズは特別な処理を行う
                node[2].each do |child|
                    stack.push(child)
                end
                operations.push([:phase, convert(node[1]), node[2].length])

            else        # それ以外は同じ
                if node[2]
                    node[2].each do |child|
                        stack.push(child)
                    end
                    operations.push([node[0], node[1], node[2].length])
                else
                    operations.push([node[0], node[1], 0])
                end
        end
    end
    operations
end

...end n_stack_radius_parser.ry/module_eval...
##### State transition tables begin ###

racc_action_table = [
    24,    25,    26,    22,    23,    11,     7,    42,     8,     5,
    27,    16,    17,    18,    19,    28,    11,    41,    10,    33,
    20,    21,    16,    17,    18,    19,    17,    18,    19,    33,
     6,    30,    33,     3,    28,    33,    17,    18,    19,    17,
    18,    19,    17,    18,    19,    33,    29,   nil,    33,   nil,
   nil,    33,    17,    18,    19,    17,    18,    19,    17,    18,
    19,    24,    25,    26,    22,    23,    24,    25,    26,    22,
    23,    24,    25,    26,    24,    25,    26 ]

racc_action_check = [
    39,    39,    39,    39,    39,    40,     5,    40,     7,     2,
    14,    40,    40,    40,    40,    14,     9,    39,     9,    22,
    11,    12,     9,     9,     9,     9,    22,    22,    22,    23,
     3,    20,    24,     1,    32,    25,    23,    23,    23,    24,
    24,    24,    25,    25,    25,    26,    16,   nil,    27,   nil,
   nil,    28,    26,    26,    26,    27,    27,    27,    28,    28,
    28,    38,    38,    38,    38,    38,    13,    13,    13,    13,
    13,    31,    31,    31,    34,    34,    34 ]

racc_action_pointer = [
   nil,    33,     2,    30,   nil,    -2,   nil,    -1,   nil,     8,
   nil,     9,     9,    64,    -3,   nil,    38,   nil,   nil,   nil,
    22,   nil,    11,    21,    24,    27,    37,    40,    43,   nil,
   nil,    69,    16,   nil,    72,   nil,   nil,   nil,    59,    -2,
    -3,   nil,   nil ]

racc_action_default = [
    -2,   -24,    -1,   -24,    -3,   -24,    43,   -24,    -6,   -24,
    -4,   -22,    -7,    -9,   -21,   -11,   -24,   -18,   -19,   -20,
   -24,    -8,   -24,   -24,   -24,   -24,   -24,   -24,   -24,   -12,
    -6,   -13,   -21,   -22,   -14,   -15,   -16,   -17,   -10,   -24,
   -24,   -23,    -5 ]

racc_goto_table = [
    14,     9,    31,    34,    35,    36,    37,    38,    39,     1,
     2,     4,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    40,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    14 ]

racc_goto_check = [
     8,     4,     7,     7,     7,     7,     7,     7,     7,     1,
     2,     3,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,     4,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     8 ]

racc_goto_pointer = [
   nil,     9,    10,     9,    -7,   nil,   nil,   -20,    -9 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,    15,    12,    13,    32 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 21, :_reduce_1,
  0, 22, :_reduce_2,
  2, 22, :_reduce_3,
  5, 23, :_reduce_4,
  5, 25, :_reduce_5,
  0, 24, :_reduce_6,
  2, 24, :_reduce_7,
  3, 24, :_reduce_8,
  1, 26, :_reduce_none,
  3, 26, :_reduce_10,
  1, 26, :_reduce_none,
  2, 26, :_reduce_12,
  3, 27, :_reduce_13,
  3, 27, :_reduce_14,
  3, 27, :_reduce_15,
  3, 27, :_reduce_16,
  3, 27, :_reduce_17,
  1, 27, :_reduce_18,
  1, 27, :_reduce_19,
  1, 27, :_reduce_20,
  1, 27, :_reduce_21,
  1, 28, :_reduce_22,
  4, 28, :_reduce_23 ]

racc_reduce_n = 24

racc_shift_n = 43

racc_token_table = {
  false => 0,
  :error => 1,
  "*" => 2,
  "/" => 3,
  "%" => 4,
  "+" => 5,
  "-" => 6,
  :PHASE => 7,
  :IDENTIFIER => 8,
  "{" => 9,
  "}" => 10,
  :DO => 11,
  ";" => 12,
  "=" => 13,
  :GOTO => 14,
  :NUMBER => 15,
  :STRING => 16,
  :BOOLEAN => 17,
  "[" => 18,
  "]" => 19 }

racc_nt_base = 20

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "\"*\"",
  "\"/\"",
  "\"%\"",
  "\"+\"",
  "\"-\"",
  "PHASE",
  "IDENTIFIER",
  "\"{\"",
  "\"}\"",
  "DO",
  "\";\"",
  "\"=\"",
  "GOTO",
  "NUMBER",
  "STRING",
  "BOOLEAN",
  "\"[\"",
  "\"]\"",
  "$start",
  "program",
  "phases",
  "phase",
  "statements",
  "do",
  "statement",
  "expr",
  "variable_address" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 8)
  def _reduce_1(val, _values, result)
    result = [:program, nil, [val[0]]]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 11)
  def _reduce_2(val, _values, result)
    result = [:phases, nil, []]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 12)
  def _reduce_3(val, _values, result)
    result[2] << val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 15)
  def _reduce_4(val, _values, result)
    result = [:phase, val[3], [[:identifier, val[1], nil]]]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 18)
  def _reduce_5(val, _values, result)
    result = [:do, val[3], [[:identifier, val[0], nil]]]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 21)
  def _reduce_6(val, _values, result)
    result = [:statements, nil, []]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 22)
  def _reduce_7(val, _values, result)
    result[2] << val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 23)
  def _reduce_8(val, _values, result)
    result[2] << val[1]
    result
  end
.,.,

# reduce 9 omitted

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 27)
  def _reduce_10(val, _values, result)
    result = [:assign_variable, nil, [val[0], val[2]]]
    result
  end
.,.,

# reduce 11 omitted

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 29)
  def _reduce_12(val, _values, result)
    result = [:goto, nil, [[:identifier, val[1], nil]]]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 32)
  def _reduce_13(val, _values, result)
    result = [:add, nil, [val[0], val[2]]]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 33)
  def _reduce_14(val, _values, result)
    result = [:dif, nil, [val[0], val[2]]]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 34)
  def _reduce_15(val, _values, result)
    result = [:mul, nil, [val[0], val[2]]]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 35)
  def _reduce_16(val, _values, result)
    result = [:div, nil, [val[0], val[2]]]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 36)
  def _reduce_17(val, _values, result)
    result = [:mod, nil, [val[0], val[2]]]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 37)
  def _reduce_18(val, _values, result)
    result = [:number, val[0], nil]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 38)
  def _reduce_19(val, _values, result)
    result = [:string, val[0], nil]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 39)
  def _reduce_20(val, _values, result)
    result = [:boolean, val[0], nil]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 40)
  def _reduce_21(val, _values, result)
    result = [:reference_variable, nil, [val[0]]]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 43)
  def _reduce_22(val, _values, result)
    result = [:identifier, val[0], nil]
    result
  end
.,.,

module_eval(<<'.,.,', 'n_stack_radius_parser.ry', 44)
  def _reduce_23(val, _values, result)
    result = [:index, nil, [val[0], val[2]]]
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class NStackRadiusParser


if __FILE__ == $0
    parser = NStackRadiusParser.new
    prg = ""
    File.open("program.rlb", "r") do |f|
        prg = f.read.chomp
    end
    pp parser.parse(prg)

end
